apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  schedule: "@monthly"
  startingDeadlineSeconds: 30
  jobTemplate:
    spec:
      template:
        spec:
          ttlSecondsAfterFinished: 60
          containers:
            - name: clearsessions
              image: dzimag/django_app:1.0
              command: ["python", "manage.py", "clearsessions"]
              envFrom:
                - secretRef:
                    name: django-secrets
          restartPolicy: OnFailure