apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: dzimag/django_app:1.0
          command: ["python", "manage.py", "migrate"]
          envFrom:
            - secretRef:
                name: django-secrets
      restartPolicy: OnFailure